if (!window.messages) {
  window.messages = {};
}

window.messages.zh_cn = {
  'title': '统一身份认证',
  'language': '<a href="javascript:changeLan(\'en\')" id="lanBtnEn">English</a>',
  'systemname': '统一身份认证',
  'systemdesc': '当前登录业务系统名称',
  'login.type.password': '密码登录',
  'login.type.qrcode': '扫码登录',
  'login.type.sms': '短信登录',
  'login.form.schoolid.title': '学工号',
  'login.form.schoolid.placeholder': '请输入学工号',
  'login.form.password.title': '密码',
  'login.form.password.placeholder': '请输入密码',
  'login.form.code.title': '验证码',
  'login.form.code.mobile': '学工号',
  'login.form.code.placeholder': '请输入短信验证码',
  'login.form.code.get': '获取验证码',
  'login.form.code.errorsend': '获取验证码操作太频繁，请稍后再试。',
  'login.form.code.notfound': '用户或手机号不存在。',
  'login.form.code.threshold': '已达到今日发送上限。',
  'login.form.code.error': '短信验证码错误。',
  'login.form.captcha.title': '验证码',
  'login.form.captcha.placeholder': '请输入图形验证码',
  'login.form.qrcode.tips': '二维码已失效',
  'login.form.qrcode.text1': '请使用微信扫描二维码登录',
  'login.form.qrcode.text2': '“统一认证”',
  'login.form.btn.login': '账号登录',
  'login.form.btn.shortlogin': '登录',
  'login.form.btn.refresh': '请点击刷新',
  'link.forgetpass': '重置密码',
  'link.signin1': '　',
  'link.signin2': '立即激活',
  'link.signin3': '帮助中心',
  'link.usercenter': '个人中心',
  'link.mp': '北邮企业微信号',
  'help.title': '帮助中心',
  'tips.title': '温馨提示：',
  'tips.text': '扫码登录前请先注册 “<span class="default-color">北邮企业微信号</span>”。',
  'tips.text1': '1. 用户名为“职工号／学号”。若忘记密码或提示密码错误，请点击“<a href="https://uc.bupt.edu.cn/#/reset/index" target="_blank" class="default-color">重置密码</a>”',
  'tips.text2': '2. “职工号／学号”见北邮通校园卡卡面',
  'tips.text3': '3. 建议浏览器：谷歌，IE(8.0+)',
  'tips.text4': '4. 扫码登录前请先注册 “北京邮电大学”',
  'tips.text5': '5. 账号密码双因子登录方法请查看：<a href="https://auth.bupt.edu.cn/authserver/cas/omg/%E5%8F%8C%E5%9B%A0%E5%AD%90%E8%AE%A4%E8%AF%81%E6%93%8D%E4%BD%9C%E6%89%8B%E5%86%8C.pdf" target="_blank" class="default-color">双因子认证操作手册</a>',
  'tips.text6': '用户名为“职工号／学号”。若忘记密码或提示密码错误，请点击“',
  'link.changeSms': '用短信验证码登录',
  'link.changePas': '用账号密码登录',
  'copyright.tip': '',
  'copyright.icp': '版权所有 © 北京邮电大学　地址：北京市西土城路10号　邮编：100876　京ICP备05064445号　京公网安备110402430070',
  'copyright.support': '',
  'copyright.browser': ''
}
